case_id: '3'
party_role: plaintiff
dataset_path: case_data_extracted.json
case_type: 故意伤害罪与正当防卫
case_category: criminal
case_state: 空闲
designated_lawyer_id: ''
assigned_lawyer_id: ''
profile: {}
source_title: 指导案例144号：张那木拉正当防卫案
